# Generated by Django 3.1 on 2020-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeduser',
            name='subscribed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
