# Generated by Django 3.1 on 2020-11-12 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0002_auto_20201112_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='form',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='form_generator.form'),
            preserve_default=False,
        ),
    ]
