# Generated by Django 3.1 on 2020-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0003_auto_20201112_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
