# Generated by Django 3.1 on 2020-09-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tenant',
        ),
        migrations.AddField(
            model_name='tenant',
            name='rental_property',
            field=models.OneToOneField(
                default=15, on_delete=django.db.models.deletion.CASCADE, to='app.property'),
            preserve_default=False,
        ),
    ]
