# Generated by Django 3.1 on 2020-09-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200926_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='rental_property',
            field=models.OneToOneField(default=14, on_delete=django.db.models.deletion.CASCADE, to='app.property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='zws_id',
            field=models.CharField(max_length=23, null=True),
        ),
    ]
