# Generated by Django 3.1 on 2020-09-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_renovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='zws_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
    ]
