# Generated by Django 3.1 on 2020-09-30 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20200928_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='user',
        ),
        migrations.AddField(
            model_name='setting',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
