# Generated by Django 3.1 on 2020-10-01 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200930_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.ManyToManyField(related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
