# Generated by Django 3.1 on 2020-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_property_zws_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='program',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_price_currency',
        ),
        migrations.AddField(
            model_name='loan',
            name='term',
            field=models.DurationField(null=True),
        ),
    ]
