# Generated by Django 3.1 on 2020-10-08 14:47

import app.utils
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201008_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='down_payment',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='This will be substracted from your initial buying price.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(help_text='Fixed interest rate. ARM support coming soon!', validators=[app.utils.percentage_validator]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.IntegerField(null=True, validators=[app.utils.term_validator]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bought_for',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Total value of the property at the moment of purchse', max_digits=20, null=True),
        ),
    ]
