# Generated by Django 3.1 on 2020-10-12 13:10

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201008_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['id'], 'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='zpid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, unique=True),
        ),
    ]
