# Generated by Django 3.1 on 2020-10-23 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201014_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='prop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.property'),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
