# Generated by Django 3.1 on 2020-10-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201026_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
