# Generated by Django 3.1 on 2020-10-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='start_date',
        ),
    ]
